# Generated by Django 4.0.3 on 2023-07-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='data')),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('gitHub', models.URLField()),
                ('linkedin', models.URLField()),
                ('cv', models.FileField(upload_to='data')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'data',
                'verbose_name_plural': 'data',
                'db_table': 'data',
                'ordering': ['name'],
            },
        ),
    ]
