# Generated by Django 4.0.3 on 2023-07-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='position_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='position_es',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
