# Generated by Django 4.0.3 on 2023-07-21 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['year'], 'verbose_name': 'Work', 'verbose_name_plural': 'Work'},
        ),
        migrations.AddField(
            model_name='work',
            name='company_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='company_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='work',
            table='Work',
        ),
    ]
