# Generated by Django 4.0.3 on 2023-07-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_work_options_work_company_en_work_company_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='company_en',
        ),
        migrations.RemoveField(
            model_name='work',
            name='company_es',
        ),
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.AddField(
            model_name='work',
            name='description_en_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='description_en_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='description_es_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='description_es_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='description_es',
            field=models.TextField(),
        ),
    ]
