# Generated by Django 4.0.3 on 2023-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_about_description_en_about_description_es'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.AddField(
            model_name='about',
            name='description_en_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_en_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_es_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_es_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_es',
            field=models.TextField(),
        ),
    ]
